# SPDX-License-Identifier: Apache-2.0
"""Config for the Bonsai DSpark drafter.

Extends the mlx_dspark DSparkConfig with:
  - family="bonsai" to distinguish Bonsai's cross-attention style from qwen3/gemma4
  - log_snr_dim: input dimension for the log-SNR sinusoidal conditioning (128)
  - log_snr_hidden: hidden dimension for log-SNR MLP (equals hidden_size)
  - log_snr_inference: fixed log-SNR scalar used at inference time

The config is loaded from the drafter's config.json (generated by convert_gguf)
or constructed programmatically.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class BonsaiDSparkConfig:
    """Config for the Bonsai DSpark drafter (6-block cross-attention, log-SNR conditioned)."""

    family: str = "bonsai"

    # core dims (from GGUF metadata)
    hidden_size: int = 5120
    vocab_size: int = 248320
    num_hidden_layers: int = 6
    intermediate_size: int = 8192
    rms_norm_eps: float = 1e-6

    # attention
    num_attention_heads: int = 16
    num_key_value_heads: int = 8
    head_dim: int = 256          # hidden_size // num_attention_heads
    attention_bias: bool = False

    # rope
    rope_theta: float = 1_000_000.0
    rope_type: str = "default"

    # dspark specifics
    block_size: int = 4
    mask_token_id: int = 151666   # Qwen3 default; overridden from GGUF if present
    target_layer_ids: list[int] = field(default_factory=lambda: [1, 16, 31, 46, 61])

    # markov + confidence
    markov_rank: int = 256
    enable_confidence_head: bool = True
    confidence_head_with_markov: bool = True

    # log-SNR conditioning (Prism extension)
    log_snr_dim: int = 128        # sinusoidal embedding input dim
    log_snr_inference: float = 10.0  # fixed log-SNR at inference (large positive = clean)

    # mlp / norm style (Bonsai uses Qwen3/Llama style)
    mlp_activation: str = "silu"
    norm_style: str = "qwen"
    use_v_norm: bool = False
    final_logit_softcapping: float | None = None
    pad_token_id: int = 0

    @property
    def attn_head_dim(self) -> int:
        return self.head_dim

    @property
    def n_kv_heads(self) -> int:
        return self.num_key_value_heads

    @property
    def scaling(self) -> float:
        return self.head_dim ** -0.5

    @property
    def rope_parameters(self) -> dict:
        return {"rope_type": self.rope_type}

    @property
    def attention_k_eq_v(self) -> bool:
        return False

    @classmethod
    def from_json(cls, path: str | Path) -> "BonsaiDSparkConfig":
        with open(path) as f:
            c = json.load(f)
        if c.get("family") != "bonsai":
            raise ValueError(
                f"{path}: expected family='bonsai', got {c.get('family')!r}. "
                f"This does not look like a Bonsai DSpark drafter config."
            )
        return cls(
            family="bonsai",
            hidden_size=c["hidden_size"],
            vocab_size=c["vocab_size"],
            num_hidden_layers=c["num_hidden_layers"],
            intermediate_size=c.get("intermediate_size", 8192),
            rms_norm_eps=c.get("rms_norm_eps", 1e-6),
            num_attention_heads=c["num_attention_heads"],
            num_key_value_heads=c.get("num_key_value_heads", 8),
            head_dim=c.get("head_dim", c["hidden_size"] // c["num_attention_heads"]),
            attention_bias=c.get("attention_bias", False),
            rope_theta=c.get("rope_theta", 1_000_000.0),
            block_size=c["block_size"],
            mask_token_id=c.get("mask_token_id", 151666),
            target_layer_ids=list(c["target_layer_ids"]),
            markov_rank=c.get("markov_rank", 256),
            enable_confidence_head=c.get("enable_confidence_head", True),
            confidence_head_with_markov=c.get("confidence_head_with_markov", True),
            log_snr_dim=c.get("log_snr_dim", 128),
            log_snr_inference=c.get("log_snr_inference", 10.0),
            final_logit_softcapping=c.get("final_logit_softcapping", None),
            pad_token_id=c.get("pad_token_id", 0),
        )

    def to_dict(self) -> dict:
        return {
            "family": self.family,
            "hidden_size": self.hidden_size,
            "vocab_size": self.vocab_size,
            "num_hidden_layers": self.num_hidden_layers,
            "intermediate_size": self.intermediate_size,
            "rms_norm_eps": self.rms_norm_eps,
            "num_attention_heads": self.num_attention_heads,
            "num_key_value_heads": self.num_key_value_heads,
            "head_dim": self.head_dim,
            "attention_bias": self.attention_bias,
            "rope_theta": self.rope_theta,
            "block_size": self.block_size,
            "mask_token_id": self.mask_token_id,
            "target_layer_ids": self.target_layer_ids,
            "markov_rank": self.markov_rank,
            "enable_confidence_head": self.enable_confidence_head,
            "confidence_head_with_markov": self.confidence_head_with_markov,
            "log_snr_dim": self.log_snr_dim,
            "log_snr_inference": self.log_snr_inference,
            "final_logit_softcapping": self.final_logit_softcapping,
            "pad_token_id": self.pad_token_id,
        }
