// Generated by omlx/admin/build_tokens.py from omlx/admin/tokens.json.
// Do not edit by hand: edit tokens.json and rerun the script.
//
// The app's type scale, in one place: every `.omlxText` / `.omlxMono` /
// `.omlxDisplay` call names one of the six steps instead of typing a size,
// so a number cannot drift back into a view.

import CoreGraphics

enum DesignTokens {
    /// The six type levels, in points.
    enum FontSize {
        static let aux: CGFloat = 12
        static let body: CGFloat = 14
        static let emphasis: CGFloat = 16
        static let section: CGFloat = 18
        static let page: CGFloat = 24
        static let kpi: CGFloat = 32

        /// Smallest size any auxiliary label may use.
        static let floor: CGFloat = 12
        /// Smallest size body copy and above may use.
        static let bodyFloor: CGFloat = 14
        /// Floor once enhanced readability is on.
        static let enhancedReadabilityFloor: CGFloat = 12
    }
}
