#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the app's design-token constants from ``tokens.json``.

``omlx/admin/tokens.json`` is the single source of truth for the type scale;
this script writes:

* ``apps/omlx-mac/Sources/Theme/DesignTokens.swift`` - the six steps and the floors

The generated file is committed, so the build never needs to run this script;
``--check`` regenerates in memory and fails when the committed copy has drifted,
which is what ``tests/test_generated_tokens.py`` runs.

The console's own custom properties are generated by the console work, from the
same file, once the console reads them.

Usage:
    python omlx/admin/build_tokens.py           # write the artifact
    python omlx/admin/build_tokens.py --check    # verify it is current
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ADMIN_DIR = Path(__file__).resolve().parent
REPO_ROOT = ADMIN_DIR.parents[1]
TOKENS_JSON = ADMIN_DIR / "tokens.json"
SWIFT_OUT = REPO_ROOT / "apps" / "omlx-mac" / "Sources" / "Theme" / "DesignTokens.swift"


def load_tokens() -> dict:
    with TOKENS_JSON.open(encoding="utf-8") as handle:
        return json.load(handle)


def render_swift(tokens: dict) -> str:
    scale = tokens["typography"]["scale"]
    floor = tokens["typography"]["floor"]

    def cg(value: float) -> str:
        text = f"{value:g}"
        return f"{text}"

    lines = [
        "// Generated by omlx/admin/build_tokens.py from omlx/admin/tokens.json.",
        "// Do not edit by hand: edit tokens.json and rerun the script.",
        "//",
        "// The app's type scale, in one place: every `.omlxText` / `.omlxMono` /",
        "// `.omlxDisplay` call names one of the six steps instead of typing a size,",
        "// so a number cannot drift back into a view.",
        "",
        "import CoreGraphics",
        "",
        "enum DesignTokens {",
        "    /// The six type levels, in points.",
        "    enum FontSize {",
    ]
    for name, step in scale.items():
        lines.append(f"        static let {name}: CGFloat = {cg(step['px'])}")
    lines += [
        "",
        "        /// Smallest size any auxiliary label may use.",
        f"        static let floor: CGFloat = {cg(floor['aux'])}",
        "        /// Smallest size body copy and above may use.",
        f"        static let bodyFloor: CGFloat = {cg(floor['body'])}",
        "        /// Floor once enhanced readability is on.",
        f"        static let enhancedReadabilityFloor: CGFloat = {cg(floor['enhancedReadability'])}",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when the generated artifact is stale.",
    )
    args = parser.parse_args()

    artifacts = {SWIFT_OUT: render_swift(load_tokens())}

    stale = []
    for path, content in artifacts.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if args.check and stale:
        for path in stale:
            print(f"stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        print("Run: python omlx/admin/build_tokens.py", file=sys.stderr)
        return 1

    if not args.check and not stale:
        print("tokens up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
