#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the design-token artifacts from ``tokens.json``.

``omlx/admin/tokens.json`` is the single source of truth; this script writes:

* ``omlx/admin/static/css/tokens.css``            - CSS custom properties + type scale
* ``apps/omlx-mac/Sources/Theme/DesignTokens.swift`` - numeric constants for the app

Both files are committed, so the build never needs to run them; ``--check``
regenerates in memory and fails when the committed copies have drifted, which
is what ``tests/test_generated_tokens.py`` runs.

Usage:
    python omlx/admin/build_tokens.py           # write both artifacts
    python omlx/admin/build_tokens.py --check    # verify the artifacts are current
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ADMIN_DIR = Path(__file__).resolve().parent
REPO_ROOT = ADMIN_DIR.parents[1]
TOKENS_JSON = ADMIN_DIR / "tokens.json"
CSS_OUT = ADMIN_DIR / "static" / "css" / "tokens.css"
SWIFT_OUT = REPO_ROOT / "apps" / "omlx-mac" / "Sources" / "Theme" / "DesignTokens.swift"

BANNER = (
    "/* Generated by omlx/admin/build_tokens.py from omlx/admin/tokens.json.\n"
    "   Do not edit by hand: edit tokens.json and rerun the script. */\n"
)

# Which entry of ``layout.widths`` the console measures pages with out of the
# box. The Status tab's layout control stores the chosen id; the ids themselves
# are pinned on both sides (``dashboard_layout.js`` WIDTH_IDS and
# ``admin/routes.py``'s validator), and tests/test_generated_tokens.py keeps the
# three lists in step.
DEFAULT_MEASURE = "default"


def load_tokens() -> dict:
    with TOKENS_JSON.open(encoding="utf-8") as handle:
        return json.load(handle)


def _theme_vars(tokens: dict, appearance: str) -> list[tuple[str, str]]:
    """Flat (custom-property, value) pairs for one appearance."""
    surface = tokens["surface"][appearance]
    text = tokens["text"][appearance]
    control = tokens["control"][appearance]
    semantic = tokens["semantic"][appearance]
    material = tokens["material"][appearance]
    badge = tokens["badge"][appearance]
    pairs = [
        ("--bg-primary", surface["bgPrimary"]),
        ("--bg-secondary", surface["bgSecondary"]),
        ("--bg-tertiary", surface["bgTertiary"]),
        ("--border-faint", surface["borderFaint"]),
        ("--border-normal", surface["borderNormal"]),
        ("--text-primary", text["primary"]),
        ("--text-secondary", text["secondary"]),
        ("--text-tertiary", text["tertiary"]),
        ("--text-danger", text["danger"]),
        ("--link-color", text["link"]),
        ("--btn-primary", control["primary"]),
        ("--btn-primary-text", control["primaryText"]),
        ("--accent-fill", control["accent"]),
        ("--accent-fill-hover", control["accentHover"]),
        ("--accent-fill-text", control["accentText"]),
        ("--switch-on", control["switchOn"]),
        ("--switch-knob", control["switchKnob"]),
        ("--btn-danger", control["danger"]),
        ("--bg-danger-hover", control["dangerHover"]),
        ("--danger-fg", control["dangerText"]),
        ("--focus-ring-color", control["focusRing"]),
        ("--focus-ring-width", f"{control['focusRingWidth']}px"),
        ("--code-bg", control["codeBg"]),
    ]
    # One variable per semantic colour, straight from the source: naming them
    # one by one is how `teal` and `purple` reached `tokens.json`, the badge
    # rules and the app's palette while never reaching this file, which left two
    # tone badges painting an undefined colour (`color-mix` with no variable
    # paints nothing) until a reader noticed the missing backgrounds.
    pairs += [
        (f"--sys-{name}", value)
        for name, value in semantic.items()
        if not name.startswith("_") and name != "accent"
    ]
    pairs += [
        ("--accent", semantic["accent"]),
        ("--topbar-bg", material["topBarBg"]),
        ("--topbar-border", material["topBarBorder"]),
        ("--scrim", material["scrim"]),
    ]
    pairs += [(f"--badge-{tone}-fg", value) for tone, value in badge.items()]
    # Label colours: `<family>` is the fill, `<family>Fg` the step that reads on
    # it, so one entry per family becomes two variables.
    label = tokens["label"][appearance]
    for name, value in label.items():
        if name.startswith("_"):
            continue
        pairs.append(
            (f"--label-{name[:-2]}-fg", value)
            if name.endswith("Fg")
            else (f"--label-{name}", value)
        )
    return pairs


def _scale_vars(tokens: dict) -> list[tuple[str, str]]:
    scale = tokens["typography"]["scale"]
    pairs: list[tuple[str, str]] = []
    for name, step in scale.items():
        pairs.append((f"--fs-{name}", f"{step['px']}px"))
    for name, step in scale.items():
        pairs.append((f"--lh-{name}", f"{step['lineHeight']}"))
    floor = tokens["typography"]["floor"]
    pairs.append(("--fs-floor", f"{floor['aux']}px"))
    pairs.append(("--fs-floor-body", f"{floor['body']}px"))
    pairs.append(("--fs-floor-enhanced", f"{floor['enhancedReadability']}px"))
    return pairs


def _geometry_vars(tokens: dict) -> list[tuple[str, str]]:
    pairs = [
        (f"--space-{name}", f"{value}px")
        for name, value in tokens["space"].items()
        if not name.startswith("_")
    ]
    pairs += [
        (f"--radius-{name}", f"{value}px") for name, value in tokens["radius"].items()
    ]
    layout = tokens["layout"]
    widths = layout["widths"]
    pairs += [
        ("--gutter", f"{layout['gutter']}px"),
        ("--container-form", f"{layout['formMaxWidth']}px"),
        ("--container-wide", f"var(--measure-{DEFAULT_MEASURE})"),
        ("--topbar-height", f"{layout['topBarHeight']}px"),
        ("--sub-tab-height", f"{layout['subTabHeight']}px"),
        ("--sticky-gap", f"{layout['stickyGap']}px"),
        (
            "--sticky-offset",
            "calc(var(--topbar-height) + var(--sub-tab-height) + var(--sticky-gap))",
        ),
    ]
    pairs += [
        (f"--measure-{name}", "none" if value == 0 else f"{value}px")
        for name, value in widths.items()
    ]
    pairs += [
        ("--kpi-min-width", f"{layout['kpiMinWidth']}px"),
        ("--heat-label-column", f"{layout['heatLabelColumn']}px"),
        ("--log-time-column", f"{layout['logTimeColumn']}px"),
        ("--log-level-column", f"{layout['logLevelColumn']}px"),
        ("--log-module-column", f"{layout['logModuleColumn']}px"),
        ("--log-row-height", f"{layout['logRowHeight']}px"),
        ("--log-occurrences-height", f"{layout['logOccurrencesHeight']}px"),
        ("--settings-rail-width", f"{layout['railWidth']}px"),
        ("--settings-rail-stack-below", f"{layout['railStackBelow']}px"),
    ]
    material = tokens["material"]
    pairs += [
        ("--topbar-blur", f"{material['topBarBlur']}px"),
        ("--topbar-saturate", f"{material['topBarSaturate']}"),
    ]
    console = tokens["console"]
    pairs += [
        (f"--duration-{name}", f"{value}ms")
        for name, value in console["duration"].items()
    ]
    pairs += [
        ("--toast-max-width", f"{console['toastMaxWidth']}px"),
        ("--palette-max-width", f"{console['paletteMaxWidth']}px"),
    ]
    elevation = tokens["elevation"]
    pairs += [
        ("--shadow-card", elevation["card"]),
        ("--shadow-popover", elevation["popover"]),
        ("--shadow-glow", elevation["glow"]),
    ]
    families = tokens["typography"]["families"]
    pairs += [("--font-sans", families["sans"]), ("--font-mono", families["mono"])]
    return pairs


def _render_block(pairs: list[tuple[str, str]], indent: str = "    ") -> str:
    width = max(len(name) for name, _ in pairs) + 1
    lines = [f"{indent}{(name + ':').ljust(width)} {value};" for name, value in pairs]
    return "\n".join(lines)


def render_css(tokens: dict) -> str:
    scale = tokens["typography"]["scale"]
    floor = tokens["typography"]["floor"]
    layout = tokens["layout"]

    scale_classes = "\n".join(
        f".text-{name} {{ font-size: var(--fs-{name}); line-height: var(--lh-{name}); }}"
        for name in scale
    )

    parts = [
        BANNER,
        "/*\n"
        " * Layer order matters: this file is loaded after the compiled Tailwind\n"
        " * utilities and before the per-page stylesheets, so the token layer wins\n"
        " * over Tailwind's default type scale while page-specific rules still win\n"
        " * over it.\n"
        " */\n",
        ":root {\n"
        + _render_block(_theme_vars(tokens, "light"))
        + "\n"
        + _render_block(_scale_vars(tokens))
        + "\n"
        + _render_block(_geometry_vars(tokens))
        + "\n}\n",
        '[data-theme="dark"] {\n'
        + _render_block(_theme_vars(tokens, "dark"))
        + "\n}\n",
        f"""html {{
    scrollbar-gutter: {layout['scrollbarGutter']};
}}

body {{
    font-family: var(--font-sans);
    /* Numbers must never reflow between polls: tabular figures everywhere. */
    font-variant-numeric: tabular-nums;
}}

/*
 * Type scale. Exactly six steps ({', '.join(f'{name} {step["px"]}px' for name, step in scale.items())});
 * use these classes (or the matching Tailwind alias) instead of a new size.
 */
{scale_classes}

/*
 * Minimum-size floor, applied globally rather than only under the
 * enhanced-readability toggle: 9px is below the auxiliary step and 11px is not
 * on the scale at all, so both snap to the nearest legal step. The
 * enhanced-readability block in base.html then lifts the auxiliary step to
 * {floor['enhancedReadability']}px.
 */
.text-\\[9px\\] {{
    font-size: var(--fs-aux);
}}

.text-\\[11px\\] {{
    font-size: var(--fs-body);
}}

/*
 * Layout skeleton: one gutter, one measure, one page frame.
 *
 * The measure is the dashboard's: ``--container-wide`` starts at the
 * ``default`` entry of ``layout.widths`` and the Status tab's layout control
 * rewrites it on :root, so choosing a wider dashboard widens every other tab
 * with it. ``full`` is ``none``: a page with no limit.
 */
.page-gutter {{
    padding-inline: var(--gutter);
}}

.page-wide {{
    max-inline-size: var(--container-wide);
    margin-inline: auto;
}}

.page-narrow {{
    max-inline-size: var(--container-form);
    margin-inline: auto;
}}

/*
 * The page frame. Two full spaces of air under the last row of controls, so a
 * button never lands on the window's bottom edge, and the gutter on both sides
 * at every width. Pages that scroll their own content (the chat shell) keep
 * their own frame but use the same two numbers.
 */
.page-frame {{
    padding-block: var(--space-6) var(--space-10);
    padding-inline: var(--gutter);
}}

/* The only translucent layer in the console. */
.topbar-material {{
    background-color: var(--topbar-bg);
    border-bottom: 1px solid var(--topbar-border);
    -webkit-backdrop-filter: blur(var(--topbar-blur)) saturate(var(--topbar-saturate));
    backdrop-filter: blur(var(--topbar-blur)) saturate(var(--topbar-saturate));
}}
""",
    ]
    return "\n".join(parts).rstrip() + "\n"


def render_swift(tokens: dict) -> str:
    scale = tokens["typography"]["scale"]
    floor = tokens["typography"]["floor"]
    layout = tokens["layout"]
    radius = tokens["radius"]
    material = tokens["material"]
    space = {
        name: value
        for name, value in tokens["space"].items()
        if not name.startswith("_")
    }

    def cg(value: float) -> str:
        text = f"{value:g}"
        return f"{text}"

    lines = [
        "// Generated by omlx/admin/build_tokens.py from omlx/admin/tokens.json.",
        "// Do not edit by hand: edit tokens.json and rerun the script.",
        "//",
        "// Numeric tokens the web console and the app share. Surfaces, text and",
        "// control colors stay with OMLXTheme, which resolves them through AppKit",
        "// dynamic system colors so the app keeps tracking System Settings.",
        "//",
        "// One vocabulary for both platforms: the console reads all of it through",
        "// the generated tokens.css, while the app wires the type scale today and",
        "// the spacing, radius, measure and line-height groups are the shared",
        "// values the next screens take instead of typing their own numbers.",
        "",
        "import CoreGraphics",
        "",
        "enum DesignTokens {",
        "    /// 8pt layout grid; `x1` is the 4pt icon-to-label gap.",
        "    enum Space {",
    ]
    for name, value in space.items():
        lines.append(f"        static let x{name}: CGFloat = {cg(value)}")
    lines += [
        "    }",
        "",
        "    enum Radius {",
    ]
    for name, value in radius.items():
        lines.append(f"        static let {name}: CGFloat = {cg(value)}")
    lines += [
        "    }",
        "",
        "    /// The six type levels, in points.",
        "    enum FontSize {",
    ]
    for name, step in scale.items():
        lines.append(f"        static let {name}: CGFloat = {cg(step['px'])}")
    lines += [
        "",
        "        /// Smallest size any auxiliary label may use.",
        f"        static let floor: CGFloat = {cg(floor['aux'])}",
        "        /// Smallest size body copy and above may use.",
        f"        static let bodyFloor: CGFloat = {cg(floor['body'])}",
        "        /// Floor once enhanced readability is on.",
        f"        static let enhancedReadabilityFloor: CGFloat = {cg(floor['enhancedReadability'])}",
        "    }",
        "",
        "    enum LineHeight {",
    ]
    for name, step in scale.items():
        lines.append(f"        static let {name}: CGFloat = {cg(step['lineHeight'])}")
    lines += [
        "    }",
        "",
        "    enum Container {",
        f"        static let gutter: CGFloat = {cg(layout['gutter'])}",
        f"        static let form: CGFloat = {cg(layout['formMaxWidth'])}",
        "        /// The measure every console page shares out of the box.",
        f"        static let measure: CGFloat = {cg(layout['widths'][DEFAULT_MEASURE])}",
        "        /// The wider measures the Status tab's layout control offers.",
        f"        static let measureWide: CGFloat = {cg(layout['widths']['wide'])}",
        f"        static let measureWider: CGFloat = {cg(layout['widths']['wider'])}",
        f"        static let rail: CGFloat = {cg(layout['railWidth'])}",
        "    }",
        "",
        "    enum Material {",
        f"        static let topBarBlur: CGFloat = {cg(material['topBarBlur'])}",
        f"        static let topBarSaturate: CGFloat = {cg(material['topBarSaturate'])}",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when a generated artifact is stale.",
    )
    args = parser.parse_args()

    tokens = load_tokens()
    artifacts = {
        CSS_OUT: render_css(tokens),
        SWIFT_OUT: render_swift(tokens),
    }

    stale = []
    for path, content in artifacts.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if args.check and stale:
        for path in stale:
            print(f"stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        print("Run: python omlx/admin/build_tokens.py", file=sys.stderr)
        return 1

    if not args.check and not stale:
        print("tokens up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
